# Change these first
owner: mings420 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: SG AWS1
    url: http://sgaws1.mings.pro:81
  - name: SG VIP1
    url: http://sgvip1.mings.pro:81
  - name: SG AWS2
    url: http://sgaws2.mings.pro:81
  - name: JP AWS1
    url: http://jpaws1.mings.pro:81
  - name: KR AWS1
    url: http://kraws1.mings.pro:81
  - name: LOND AWS1
    url: http://lond1.mings.pro:81

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: mings420.github.io
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitor server status for **mingstunnel**"
  introMessage: This is a real-time server status page..
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
